
services:
  # Container do Banco de Dados
  db:
    image: postgres:15-alpine
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_DB: agendamentos_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # Container da Aplicação Spring Boot
  app:
    build: .
    container_name: spring-app
    restart: always
    ports:
      # A porta 8081 do container será exposta na porta 8082 do seu computador
      - "8082:8081"
    depends_on:
      - db
    environment:
      # O Spring Boot vai ler essas variáveis de ambiente e sobrescrever o application.properties!
      # Note que a URL usa "db" em vez de "localhost" para achar o container do PostgreSQL
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/agendamentos_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: admin
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      # Informa ao Spring para rodar na porta 8081 DENTRO do container
      SERVER_PORT: 8081

# Volume para os dados do banco não sumirem quando o container desligar
volumes:
<<<<<<< HEAD
  postgres_data:
    name: postgres_data_global
=======
  postgres_data:
>>>>>>> 0d76a73c56544c4fa053745bbed71e2df4ff5901
