spring.application.name=ProjetoBack
spring.output.ansi.enabled=always
# ===============================
# CONFIGURAÇÃO DO BANCO DE DADOS
# ===============================
# ATENÇÃO: Para desenvolvimento local, ajuste a URL, usuário e senha.
# Ao usar o Docker Compose, estas propriedades serão sobrescritas pelas variáveis de ambiente.
spring.datasource.url=jdbc:postgresql://localhost:5432/agendamentos_db
spring.datasource.username=postgres
spring.datasource.password=admin
spring.datasource.driver-class-name=org.postgresql.Driver

# ===============================
# CONFIGURAÇÃO DO JPA / HIBERNATE
# ===============================
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# A opção 'update' cria ou atualiza as tabelas automaticamente com base nas suas classes Java.
# Ótimo para desenvolvimento, mas use com cautela em produção (prefira migrações com Flyway/Liquibase).
spring.jpa.hibernate.ddl-auto=update

# Exibe no console os comandos SQL que o Hibernate está executando (ótimo para debugar).
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

api.security.token.secret=${JWT_SECRET:my-secret-key}

# ===============================
# CONFIGURAÇÃO DO SERVIDOR WEB
# ===============================
server.port=8081
